import sys
from engine.core.ids import TGObject

# Event type IDs.  SDK uses int constants from App.py; here we pick a stable
# value that won't collide with the SDK's ET_INPUT_FIRE_* range (those are
# Appc-side constants exposed via App.py:13834+).
ET_KEYBOARD_EVENT: int = 0x1000
ET_WEAPON_HIT:     int = 0x1100  # reserved range above input-event ids


class TGEvent(TGObject):
    def __init__(self):
        super().__init__()
        self._event_type: int = 0
        self._destination: "TGEventHandlerObject | None" = None
        self._source: "TGObject | None" = None

    def SetEventType(self, event_type: int) -> None:
        self._event_type = event_type

    def GetEventType(self) -> int:
        return self._event_type

    def SetDestination(self, dest: "TGEventHandlerObject") -> None:
        self._destination = dest

    def GetDestination(self) -> "TGEventHandlerObject | None":
        return self._destination

    def SetSource(self, source: "TGObject") -> None:
        self._source = source

    def GetSource(self) -> "TGObject | None":
        return self._source


def TGEvent_Create() -> TGEvent:
    return TGEvent()


class TGBoolEvent(TGEvent):
    """Boolean-carrying event subclass.  Used by ET_INPUT_FIRE_* events to
    signal bFiring=1 (start) / bFiring=0 (stop).  See sdk/Build/scripts/
    TacticalInterfaceHandlers.py:391 — FireWeapons reads pEvent.GetBool()."""
    def __init__(self):
        super().__init__()
        self._value: int = 0

    def SetBool(self, v) -> None:
        self._value = 1 if v else 0

    def GetBool(self) -> int:
        return self._value


def TGBoolEvent_Create() -> TGBoolEvent:
    return TGBoolEvent()


class TGKeyboardEvent(TGEvent):
    """Carries a unicode key code + key state (KS_KEYDOWN / KS_KEYUP).
    Generated by g_kInputManager when a registered key transitions; consumed
    by g_kKeyboardBinding which translates it into ET_INPUT_FIRE_* events.
    """
    KS_KEYDOWN   = 0
    KS_KEYUP     = 1
    KS_KEYREPEAT = 2
    KS_NORMAL    = 3   # character-input event (e.g. printable keys)

    def __init__(self):
        super().__init__()
        self._event_type = ET_KEYBOARD_EVENT
        self._unicode_key: int = 0
        self._key_state: int = 0

    def SetUnicodeKey(self, k) -> None:
        self._unicode_key = int(k)

    def GetUnicodeKey(self) -> int:
        return self._unicode_key

    def SetKeyState(self, s) -> None:
        self._key_state = int(s)

    def GetKeyState(self) -> int:
        return self._key_state


class WeaponHitEvent(TGEvent):
    """Weapon-impact event.  Broadcast by engine.appc.combat.apply_hit
    after damage is routed.  Mission scripts subscribe to ET_WEAPON_HIT
    (per-ship or broadcast) to react — e.g. MissionLib.FriendlyFireHandler
    triggers XO dialogue when the player damages a friendly NPC.

    Inherits TGEvent's _source / Set/GetSource for the firing ship; the
    weapon-specific surface adds target, damage, hit-point, subsystem.
    """
    def __init__(self):
        super().__init__()
        self._event_type = ET_WEAPON_HIT
        self._target = None
        self._damage: float = 0.0
        self._hit_point = None
        self._subsystem = None

    def GetTarget(self):              return self._target
    def SetTarget(self, tgt) -> None: self._target = tgt
    def GetDamage(self) -> float:     return self._damage
    def SetDamage(self, v) -> None:   self._damage = float(v)
    def GetHitPoint(self):            return self._hit_point
    def SetHitPoint(self, p) -> None: self._hit_point = p
    def GetSubsystem(self):           return self._subsystem
    def SetSubsystem(self, s) -> None: self._subsystem = s


def _resolve_handler(qualified_name: str):
    """Resolve 'module.func' to the callable, or None if not found."""
    dot = qualified_name.rfind(".")
    if dot == -1:
        return None
    mod_name, func_name = qualified_name[:dot], qualified_name[dot + 1:]
    mod = sys.modules.get(mod_name)
    if mod is None:
        return None
    return getattr(mod, func_name, None)


class TGEventHandlerObject(TGObject):
    def __init__(self):
        super().__init__()
        # {event_type: [qualified_handler_name, ...]}
        self._handlers: dict[int, list[str]] = {}

    def AddPythonFuncHandlerForInstance(self, event_type: int, qualified_name: str) -> None:
        self._handlers.setdefault(event_type, []).append(qualified_name)

    def RemoveHandlerForInstance(self, event_type: int, qualified_name: str) -> None:
        handlers = self._handlers.get(event_type, [])
        if qualified_name in handlers:
            handlers.remove(qualified_name)

    def RemoveAllInstanceHandlers(self) -> None:
        self._handlers.clear()

    def ProcessEvent(self, event: TGEvent) -> None:
        for name in self._handlers.get(event.GetEventType(), []):
            fn = _resolve_handler(name)
            if fn is not None:
                fn(self, event)


class TGEventManager(TGObject):
    def __init__(self):
        super().__init__()
        # {event_type: [(dest_obj, qualified_name), ...]}
        self._broadcast_handlers: dict[int, list[tuple["TGEventHandlerObject", str]]] = {}

    def AddBroadcastPythonFuncHandler(
        self, event_type: int, dest: "TGEventHandlerObject", qualified_name: str, *extra
    ) -> None:
        self._broadcast_handlers.setdefault(event_type, []).append((dest, qualified_name))

    def RemoveBroadcastHandler(
        self, event_type: int, dest: "TGEventHandlerObject", qualified_name: str
    ) -> None:
        handlers = self._broadcast_handlers.get(event_type, [])
        entry = (dest, qualified_name)
        if entry in handlers:
            handlers.remove(entry)

    RemoveBroadcastHandlerForInstance = RemoveBroadcastHandler

    def AddEvent(self, event: TGEvent) -> None:
        dest = event.GetDestination()
        if dest is not None:
            dest.ProcessEvent(event)
        for bd, name in self._broadcast_handlers.get(event.GetEventType(), []):
            fn = _resolve_handler(name)
            if fn is not None:
                fn(bd, event)
