import sys
from engine.core.ids import TGObject

# Event type IDs.  SDK uses int constants from App.py; here we pick a stable
# value that won't collide with the SDK's ET_INPUT_FIRE_* range (those are
# Appc-side constants exposed via App.py:13834+).
ET_KEYBOARD_EVENT: int = 0x1000
ET_WEAPON_HIT:     int = 0x1100  # reserved range above input-event ids


class TGEvent(TGObject):
    def __init__(self):
        super().__init__()
        self._event_type: int = 0
        self._destination: "TGEventHandlerObject | None" = None
        self._source: "TGObject | None" = None

    def SetEventType(self, event_type: int) -> None:
        self._event_type = event_type

    def GetEventType(self) -> int:
        return self._event_type

    def SetDestination(self, dest: "TGEventHandlerObject") -> None:
        self._destination = dest

    def GetDestination(self) -> "TGEventHandlerObject | None":
        return self._destination

    def SetSource(self, source: "TGObject") -> None:
        self._source = source

    def GetSource(self) -> "TGObject | None":
        return self._source


def TGEvent_Create() -> TGEvent:
    return TGEvent()


class TGBoolEvent(TGEvent):
    """Boolean-carrying event subclass.  Used by ET_INPUT_FIRE_* events to
    signal bFiring=1 (start) / bFiring=0 (stop).  See sdk/Build/scripts/
    TacticalInterfaceHandlers.py:391 — FireWeapons reads pEvent.GetBool()."""
    def __init__(self):
        super().__init__()
        self._value: int = 0

    def SetBool(self, v) -> None:
        self._value = 1 if v else 0

    def GetBool(self) -> int:
        return self._value


def TGBoolEvent_Create() -> TGBoolEvent:
    return TGBoolEvent()


class TGKeyboardEvent(TGEvent):
    """Carries a unicode key code + key state (KS_KEYDOWN / KS_KEYUP).
    Generated by g_kInputManager when a registered key transitions; consumed
    by g_kKeyboardBinding which translates it into ET_INPUT_FIRE_* events.
    """
    KS_KEYDOWN   = 0
    KS_KEYUP     = 1
    KS_KEYREPEAT = 2
    KS_NORMAL    = 3   # character-input event (e.g. printable keys)

    def __init__(self):
        super().__init__()
        self._event_type = ET_KEYBOARD_EVENT
        self._unicode_key: int = 0
        self._key_state: int = 0

    def SetUnicodeKey(self, k) -> None:
        self._unicode_key = int(k)

    def GetUnicodeKey(self) -> int:
        return self._unicode_key

    def SetKeyState(self, s) -> None:
        self._key_state = int(s)

    def GetKeyState(self) -> int:
        return self._key_state


class WeaponHitEvent(TGEvent):
    """Weapon-impact event.  Broadcast by engine.appc.combat.apply_hit
    after damage is routed.  Mission scripts subscribe to ET_WEAPON_HIT
    (per-ship or broadcast) to react — e.g. MissionLib.FriendlyFireHandler
    triggers XO dialogue when the player damages a friendly NPC.

    Inherits TGEvent's _source / Set/GetSource for the firing ship; the
    weapon-specific surface adds target, damage, hit-point, subsystem.
    """
    def __init__(self):
        super().__init__()
        self._event_type = ET_WEAPON_HIT
        self._target = None
        self._damage: float = 0.0
        self._hit_point = None
        self._subsystem = None

    def GetTarget(self):              return self._target
    def SetTarget(self, tgt) -> None: self._target = tgt
    def GetDamage(self) -> float:     return self._damage
    def SetDamage(self, v) -> None:   self._damage = float(v)
    def GetHitPoint(self):            return self._hit_point
    def SetHitPoint(self, p) -> None: self._hit_point = p
    def GetSubsystem(self):           return self._subsystem
    def SetSubsystem(self, s) -> None: self._subsystem = s


def _resolve_handler(qualified_name: str):
    """Resolve 'module.func' to the callable, or None if not found."""
    dot = qualified_name.rfind(".")
    if dot == -1:
        return None
    mod_name, func_name = qualified_name[:dot], qualified_name[dot + 1:]
    mod = sys.modules.get(mod_name)
    if mod is None:
        return None
    return getattr(mod, func_name, None)


class TGEventHandlerObject(TGObject):
    def __init__(self):
        super().__init__()
        # {event_type: [qualified_handler_name, ...]}
        self._handlers: dict[int, list[str]] = {}

    def AddPythonFuncHandlerForInstance(self, event_type: int, qualified_name: str) -> None:
        self._handlers.setdefault(event_type, []).append(qualified_name)

    def RemoveHandlerForInstance(self, event_type: int, qualified_name: str) -> None:
        handlers = self._handlers.get(event_type, [])
        if qualified_name in handlers:
            handlers.remove(qualified_name)

    def RemoveAllInstanceHandlers(self) -> None:
        self._handlers.clear()

    def ProcessEvent(self, event: TGEvent) -> None:
        for name in self._handlers.get(event.GetEventType(), []):
            fn = _resolve_handler(name)
            if fn is not None:
                fn(self, event)


class TGPythonInstanceWrapper(TGEventHandlerObject):
    """Bridge between TGEventHandlerObject (the event-manager's destination
    type) and a Python instance's named methods. SDK conditions use this to
    receive events at a wrapper and dispatch to a method on the wrapped
    Python instance.

    Pattern (from sdk/.../Conditions/ConditionExists.py):
        self.pEventHandler = App.TGPythonInstanceWrapper()
        self.pEventHandler.SetPyWrapper(self)
        App.g_kEventManager.AddBroadcastPythonMethodHandler(
            App.ET_DELETE_OBJECT_PUBLIC, self.pEventHandler, "Deleted", obj)
    """
    def __init__(self):
        super().__init__()
        self._py_wrapper = None
        # Dict initialized eagerly because TGObject.__getattr__ returns a
        # _Stub (not None) for missing attrs, so the lazy `getattr(..., None)`
        # idiom would silently mis-route registrations into a throwaway Stub.
        self._method_handlers: dict[int, list[str]] = {}

    def SetPyWrapper(self, instance) -> None:
        self._py_wrapper = instance

    def GetPyWrapper(self):
        return self._py_wrapper

    def AddPythonMethodHandlerForInstance(self, event_type: int, method_name: str) -> None:
        """Register a self-targeted method handler. Used by SDK conditions
        that listen for events sent directly to the wrapper (e.g. timer
        events) rather than broadcast across the bus."""
        self._method_handlers.setdefault(event_type, []).append(method_name)

    def ProcessEvent(self, event):
        """Dispatch a direct-to-wrapper event to the registered method on
        the wrapped Python instance. Overrides the parent's qualified-
        function dispatch since this wrapper uses instance methods."""
        names = self._method_handlers.get(event.GetEventType(), [])
        py = self._py_wrapper
        if py is None:
            return
        for name in names:
            fn = getattr(py, name, None)
            if fn is not None:
                fn(event)


class TGEventManager(TGObject):
    def __init__(self):
        super().__init__()
        # {event_type: [(dest_obj, qualified_name), ...]}
        self._broadcast_handlers: dict[int, list[tuple["TGEventHandlerObject", str]]] = {}
        # {event_type: [(wrapper, method_name, target), ...]}; eager init —
        # see TGPythonInstanceWrapper note about TGObject.__getattr__ stubs.
        self._method_handlers: dict[
            int, list[tuple["TGPythonInstanceWrapper", str, object]]
        ] = {}

    def AddBroadcastPythonFuncHandler(
        self, event_type: int, dest: "TGEventHandlerObject", qualified_name: str, *extra
    ) -> None:
        self._broadcast_handlers.setdefault(event_type, []).append((dest, qualified_name))

    def AddBroadcastPythonMethodHandler(
        self, event_type: int, wrapper: "TGPythonInstanceWrapper",
        method_name: str, target=None,
    ) -> None:
        """Method-based broadcast handler. Mirrors AddBroadcastPythonFuncHandler
        but dispatches `getattr(wrapper.GetPyWrapper(), method_name)(evt)`
        instead of a module-qualified function. `target` (if given) restricts
        dispatch to events whose destination matches `target` by identity;
        None matches all events of `event_type`."""
        self._method_handlers.setdefault(event_type, []).append(
            (wrapper, method_name, target)
        )

    def RemoveBroadcastHandler(
        self, event_type: int, dest_or_wrapper, qualified_name_or_method: str,
        target=None,
    ) -> None:
        """Remove a previously-added broadcast handler.

        Supports both `(eType, dest, qualified_name)` (func handler, legacy)
        and `(eType, wrapper, method_name[, target])` (method handler, new).
        Falls through to the func-handler list first; if not found there,
        tries the method-handler list."""
        # Func handlers: (dest, qualified_name) tuples.
        func_handlers = self._broadcast_handlers.get(event_type, [])
        entry = (dest_or_wrapper, qualified_name_or_method)
        if entry in func_handlers:
            func_handlers.remove(entry)
            return
        # Method handlers: (wrapper, method_name, target) tuples.
        method_handlers = self._method_handlers.get(event_type, [])
        entry_m = (dest_or_wrapper, qualified_name_or_method, target)
        if entry_m in method_handlers:
            method_handlers.remove(entry_m)

    RemoveBroadcastHandlerForInstance = RemoveBroadcastHandler

    def AddEvent(self, event: TGEvent) -> None:
        dest = event.GetDestination()
        if dest is not None and isinstance(dest, TGEventHandlerObject):
            dest.ProcessEvent(event)
        # Func-broadcast handlers (existing).
        for bd, name in self._broadcast_handlers.get(event.GetEventType(), []):
            fn = _resolve_handler(name)
            if fn is not None:
                fn(bd, event)
        # Method-broadcast handlers (new).
        for wrapper, method_name, target in self._method_handlers.get(
            event.GetEventType(), []
        ):
            if target is not None and event.GetDestination() is not target:
                continue
            py = wrapper.GetPyWrapper()
            if py is not None:
                method = getattr(py, method_name, None)
                if method is not None:
                    method(event)
